title: "Search sandbox"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
baseurl: ""
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
